version: "3"
services:
  database:
    image: mariadb:10.6
    ports:
      - "3310:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=phuberbd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    restart: always
